spring:
  application:
    name: ecom-application

  datasource:
    url: jdbc:h2:mem:ecomdb
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true